services:
  influxdb:
    image: influxdb:2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: twelve12
      DOCKER_INFLUXDB_INIT_ORG: CDN-In-A-Box
      DOCKER_INFLUXDB_INIT_BUCKET: default # required for the initial bootstrapping, not in use after that
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 8086:8086
